# Generated by Django 5.0.1 on 2024-01-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='joined_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone',
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(default=0.1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to='members_pictures/'),
            preserve_default=False,
        ),
    ]
