# Generated by Django 5.0.1 on 2024-01-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_member_firstname_remove_member_joined_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='member',
            name='Ingredients',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='cook',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
