# Generated by Django 5.0.1 on 2024-01-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_member_profile_picture_member_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='cook',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
