# Generated by Django 5.0.1 on 2024-01-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_cook'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='img',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='s_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
