# Generated by Django 5.0.1 on 2024-01-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='re_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('e_name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='ClASS',
        ),
    ]
