# Generated by Django 5.0.1 on 2024-01-09 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_member_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='ClASS',
            new_name='class_val',
        ),
    ]
